# Generated by Django 4.1.4 on 2022-12-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Instruction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("instruction", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "Instruction",
                "verbose_name_plural": "Instructions",
            },
        ),
    ]
