# Generated by Django 4.1.4 on 2023-11-08 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("no_of_questions", models.IntegerField(default=30)),
                ("hint1_revealed", models.IntegerField(default=50)),
                ("hint2_revealed", models.IntegerField(default=100)),
            ],
            options={
                "verbose_name": "quiz",
                "verbose_name_plural": "quizzes",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.FileField(upload_to="image")),
                ("hint1", models.CharField(max_length=100)),
                ("hint2", models.CharField(max_length=100)),
                ("answer", models.CharField(max_length=100)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("Easy", "EASY"),
                            ("Moderate", "MODERATE"),
                            ("Hard", "HARD"),
                        ],
                        default="Easy",
                        max_length=50,
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quizapp.quiz"
                    ),
                ),
            ],
            options={
                "verbose_name": "question",
                "verbose_name_plural": "questions",
            },
        ),
        migrations.CreateModel(
            name="Progress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.IntegerField(default=0)),
                ("hits", models.IntegerField(default=0)),
                ("points", models.IntegerField(default=0)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quizapp.quiz"
                    ),
                ),
                (
                    "usr",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ordering",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userType", models.CharField(default="BASIC", max_length=50)),
                (
                    "question",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="quizapp.question",
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="quizapp.quiz",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[("Login", "LOGIN"), ("Thiran", "THIRAN")],
                        default="Thiran",
                        max_length=50,
                    ),
                ),
                ("year", models.IntegerField(default=2023)),
                ("eventLogo", models.FileField(upload_to="images")),
                ("logo", models.FileField(upload_to="images")),
                ("startBy", models.DateTimeField()),
                ("endBy", models.DateTimeField()),
                ("easyScore", models.IntegerField(default=240)),
                ("moderateScore", models.IntegerField(default=500)),
                ("hardScore", models.IntegerField(default=1000)),
                ("commonMailId", models.EmailField(max_length=254)),
                (
                    "coordinator1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Coordinator1",
                        to="user.coordinator",
                    ),
                ),
                (
                    "coordinator2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Coordinator2",
                        to="user.coordinator",
                    ),
                ),
                (
                    "mainQuiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="main",
                        to="quizapp.quiz",
                    ),
                ),
                (
                    "practiceQuiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practice",
                        to="quizapp.quiz",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CurrentStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.IntegerField(default=0)),
                ("score", models.IntegerField(default=0)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quizapp.quiz"
                    ),
                ),
                (
                    "usr",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
