# Generated by Django 4.1.4 on 2023-02-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizapp", "0002_progress_log_currentstatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="progress",
            name="points",
            field=models.IntegerField(default=0),
        ),
    ]
