# Generated by Django 4.1.4 on 2023-02-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizapp", "0003_progress_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="currentstatus",
            name="score",
            field=models.IntegerField(default=0),
        ),
    ]
