# Generated by Django 4.1.4 on 2023-03-20 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("quizapp", "0004_currentstatus_score"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ordering",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="quizapp.question",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Log",
        ),
    ]
