# Generated by Django 4.1.4 on 2023-03-20 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("quizapp", "0005_ordering_delete_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordering",
            name="quiz",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="quizapp.quiz",
            ),
        ),
        migrations.AddField(
            model_name="ordering",
            name="userType",
            field=models.CharField(default="BASIC", max_length=50),
        ),
    ]
