# Generated by Django 4.1.4 on 2023-09-10 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_candidate_batch"),
        ("quizapp", "0006_ordering_quiz_ordering_usertype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currentstatus",
            name="usr",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user.candidate"
            ),
        ),
        migrations.AlterField(
            model_name="progress",
            name="usr",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user.candidate"
            ),
        ),
    ]
