# Generated by Django 4.1.4 on 2022-12-27 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
        ("instruction", "0002_instruction_quiz"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instruction",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="quiz.quiz"
            ),
        ),
    ]
