# Generated by Django 4.1.4 on 2023-02-10 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0004_nethuntcoordinator_coordinator"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("no_of_questions", models.IntegerField()),
                ("hint1_revealed", models.IntegerField()),
                ("hint2_revealed", models.IntegerField()),
            ],
            options={
                "verbose_name": "quiz",
                "verbose_name_plural": "quizzes",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.FileField(upload_to="image")),
                ("hint1", models.CharField(max_length=100)),
                ("hint2", models.CharField(max_length=100)),
                ("answer", models.CharField(max_length=100)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("Easy", "EASY"),
                            ("Moderate", "MODERATE"),
                            ("Hard", "HARD"),
                        ],
                        default="Easy",
                        max_length=50,
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="game.quiz"
                    ),
                ),
            ],
            options={
                "verbose_name": "question",
                "verbose_name_plural": "questions",
            },
        ),
        migrations.CreateModel(
            name="Info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[("Login", "LOGIN"), ("Thiran", "THIRAN")],
                        default="Thiran",
                        max_length=50,
                    ),
                ),
                ("year", models.IntegerField(default=2023)),
                ("eventLogo", models.FileField(upload_to="images")),
                ("logo", models.FileField(upload_to="images")),
                ("startBy", models.DateTimeField()),
                ("endBy", models.DateTimeField()),
                ("easyScore", models.IntegerField(default=240)),
                ("moderateScore", models.IntegerField(default=500)),
                ("hardScore", models.IntegerField(default=1000)),
                ("commonMailId", models.EmailField(max_length=254)),
                (
                    "coordinator1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Coordinator1",
                        to="user.coordinator",
                    ),
                ),
                (
                    "coordinator2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Coordinator2",
                        to="user.coordinator",
                    ),
                ),
            ],
        ),
    ]
