# Generated by Django 4.1.4 on 2023-02-13 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_temp"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Temp",
        ),
    ]
