# Generated by Django 4.1.4 on 2023-01-10 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="College",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("collegeName", models.CharField(max_length=200)),
                ("collegeCity", models.CharField(max_length=50)),
            ],
        ),
    ]
