# Generated by Django 4.1.4 on 2023-01-23 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0004_nethuntcoordinator_coordinator"),
    ]

    operations = [
        migrations.CreateModel(
            name="Info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flag", models.BooleanField(default=False)),
                ("logo", models.FileField(upload_to="images")),
                ("startBy", models.DateTimeField()),
                ("endtBy", models.DateTimeField()),
                (
                    "coordinator1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Coordinator1",
                        to="user.coordinator",
                    ),
                ),
                (
                    "coordinator2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Coordinator2",
                        to="user.coordinator",
                    ),
                ),
            ],
        ),
    ]
