# Generated by Django 4.1.4 on 2023-01-31 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0004_alter_info_commonmailid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="info",
            name="flag",
        ),
    ]
