# Generated by Django 4.1.4 on 2023-01-31 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0005_remove_info_flag"),
    ]

    operations = [
        migrations.AddField(
            model_name="info",
            name="event",
            field=models.CharField(
                choices=[("Login", "LOGIN"), ("Thiran", "THIRAN")],
                default="Thiran",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="info",
            name="year",
            field=models.IntegerField(default=2023),
        ),
        migrations.AddField(
            model_name="question",
            name="difficulty",
            field=models.CharField(
                choices=[("Easy", "EASY"), ("Moderate", "MODERATE"), ("Hard", "HARD")],
                default="Easy",
                max_length=50,
            ),
        ),
    ]
