# Generated by Django 4.1.4 on 2023-01-31 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0006_info_event_info_year_question_difficulty"),
    ]

    operations = [
        migrations.RenameField(
            model_name="info",
            old_name="endtBy",
            new_name="endBy",
        ),
    ]
