# Generated by Django 4.1.4 on 2023-01-31 18:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0007_rename_endtby_info_endby"),
    ]

    operations = [
        migrations.AddField(
            model_name="info",
            name="eventLogo",
            field=models.FileField(
                default=django.utils.timezone.now, upload_to="images"
            ),
            preserve_default=False,
        ),
    ]
