# Generated by Django 4.1.4 on 2023-01-10 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("college", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                ("current_level", models.IntegerField(default=1)),
                ("status", models.CharField(default="offline", max_length=10)),
                (
                    "collegeName",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="college.college",
                    ),
                ),
            ],
        ),
    ]
