# Generated by Django 4.1.4 on 2023-01-22 07:01

from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="College",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("collegeName", models.CharField(max_length=100)),
                ("collegeCity", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_level", models.IntegerField(default=1)),
                ("status", models.CharField(default="offline", max_length=10)),
                (
                    "phone",
                    models.CharField(
                        max_length=10, validators=[user.models.validPhone]
                    ),
                ),
                (
                    "college",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.college"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.nethuntcandidate",
                    ),
                ),
            ],
        ),
    ]
