# Generated by Django 4.1.4 on 2023-01-10 03:35

from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ("college", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="collegeName",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="college.college",
                validators=[user.models.validCollege],
            ),
        ),
    ]
