# Generated by Django 4.1.4 on 2023-01-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="nethuntuser",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="nethuntuser",
            name="is_candidate",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="nethuntuser",
            name="is_coordinator",
            field=models.BooleanField(default=False),
        ),
    ]
