# Generated by Django 4.1.4 on 2023-01-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_nethuntuser_is_admin_nethuntuser_is_candidate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nethuntuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
