# Generated by Django 4.1.4 on 2023-01-22 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_college_candidate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nethuntuser",
            name="username",
        ),
    ]
