# Generated by Django 4.1.4 on 2023-01-23 12:07

from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_remove_nethuntuser_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="NethuntCoordinator",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("user.nethuntuser",),
        ),
        migrations.CreateModel(
            name="Coordinator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.FileField(upload_to="images")),
                (
                    "phone",
                    models.CharField(
                        max_length=10, validators=[user.models.validPhone]
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.nethuntcoordinator",
                    ),
                ),
            ],
        ),
    ]
