# Generated by Django 4.1.4 on 2023-04-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_nethuntcoordinator_coordinator"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="userType",
            field=models.CharField(
                choices=[("Basic", "BASIC"), ("Alumni", "ALUMNI")],
                default="Basic",
                max_length=50,
            ),
        ),
    ]
