# Generated by Django 4.1.4 on 2023-04-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_candidate_usertype"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="batch",
            field=models.IntegerField(default=2021),
        ),
    ]
